version: "3.1"
services:
  app:
    image: surehelp_userapp
    container_name: surehelp_userapp_php
    build: 
      context: .
      dockerfile: .
    restart: "no"
    ports:
      - 80:80
      - 8000:8000
    volumes:
      - ./:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - surehelp_userapp

    command: "php artisan serve --host=0.0.0.0 --port=8000"

   

  db:
    image: mysql:latest
    container_name: mysql_db_surehelp_userapp
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db-data_surehelp_userapp:/docker-entrypoint-initdb.d
      - db-data_surehelp_userapp:/var/lib/mysql
    networks:
      - surehelp_userapp
   
  
  phpmyadmin:
    image: phpmyadmin:5.2.0-apache
    restart: "no"
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - surehelp_userapp


networks:
  surehelp_userapp:
    driver: bridge



volumes:
  db-data_surehelp_userapp:
  